### ISSUE TITLE
android平台

### ISSUE THREAD

**Issue by lovedabaozi** [zl03jsj/mupdf#1]
您好，你这个项目 android平台上的demo跑步起来，缺少so库

**Comment by lovedabaozi** [comment]
![image](https://user-images.githubusercontent.com/13343772/35318537-c3170876-0116-11e8-8f2e-521360d1972c.png)

**Comment by zl03jsj** [comment]
要先运行make  generated, 这个name-table.h是运行make后自动生成的.
cd /path/of/mupdf
make -f makfile generated

**Comment by zl03jsj** [comment]
缺少的so是mupdf的动态库, 需要你自己根据你的ndk和android设备的架构来编译.

**Comment by lovedabaozi** [comment]
![image](https://user-images.githubusercontent.com/13343772/35427929-40a78130-02a7-11e8-8a55-bd57ab9052ff.png)
您好 ，还是编译不过去，您能帮忙提供一个编译好的so库吗  谢谢

**Comment by zl03jsj** [comment]
clone 的时候, 运行
git clone --recursive https://github.com/zl03jsj/mupdf
不然sub-module就没有被clone下来, 你会少文件的.

**Comment by lovedabaozi** [comment]
您好，按您说的这个clone  还是缺少文件，您能提供一个编译好的so库版本吗？

**Comment by zl03jsj** [comment]
好的，有空发你啊

发自我的 iPhone
