### ISSUE TITLE
使用透明图片作为签名外观，背景为

### ISSUE THREAD

**Issue by zfx41810** [zl03jsj/mupdf#4]
你好，我是用透明的png或gif作为签名外观时，得到的签名是黑色背景。但当我使用白色背景的png时，得到的签名外观是透明的 ，请问是哪个参数的问题。

fz_begin_group(ctx, dev, rect, cs, 0, 0, FZ_BLEND_DARKEN, 1);
fz_fill_image(ctx, dev, img, image_ctm, 1.0f, NULL);
fz_end_group(ctx, dev);

是否是这段代码的问题，谢谢

**Comment by zl03jsj** [comment]
fz_begin_group(ctx, dev, rect, cs, 0, 0, FZ_BLEND_DARKEN, 1);
是这个fz_blend_darken, 看看有一些其他的什么模式.

**Comment by 124327288** [comment]
我遇到了一样的情况。。。不过是用的其他的函数。在mupdf1.17里面
