### ISSUE TITLE
执行 pdftest 命令时出现 cycle in page tree 错误

### ISSUE THREAD

**Issue by wonderffee** [zl03jsj/mupdf#5]
./pdftest
main is call
error: cycle in page tree
warning: cycle in page tree

搞不明白出现这个的原因，有人知道吗

**Comment by zl03jsj** [comment]
是不是pdf文件解析出现了问题啊..
先换一个pdf文件试试看.先找到问题先. @wonderffee

**Comment by wonderffee** [comment]
应该不是pdf 文件的问题，因为首先就是用的你提供的pdf（在iOS源码中的）来测试的，后来自己另找了一份pdf也是同样的问题 @zl03jsj

**Comment by zl03jsj** [comment]
ok, 回头我有空我会看看的. @wonderffee

**Comment by zl03jsj** [comment]
@wonderffee 
我测试了一下,这个错误的原因是, 在pdf_sample.c 文件, 303行,

testAddAnnotation(ctx, doc, 17, ofile);

testAddAnnotation的第三个参数, 表示pageno, 你的pdf文件, 没有17这么多页, 所以会报错了. 
我已经修改了这个参数, 默认为0
